# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-chart
  namespace: ns-postgres-production
spec:
  interval: 1m
  chart:
    spec:
      chart: ../../../charts/postgres/
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    containers:
        image: "gcr.io/capable-conduit-348311/postgres:latest"