apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: java-chart
  namespace: ns-java-production
spec:
  interval: 1m
  chart:
    spec:
      chart: ../../../charts/java/
      version: 0.1.2
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m