apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-dso-gke-postgres
  labels:
    app: postgres-app
spec:
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres-app
          image: dso-gke-postgres/image
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "db"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
