apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-postgres-production
resources:
  - namespace.yaml
  - ../../base/postgres
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
