apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-kafdrop
  labels:
    app: kafdrop
spec:
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop
          env:
            - name: KAFKA_BROKERCONNECT
              value: "{{ .Values.KAFKA_BROKERCONNECT }}"
            - name: JVM_OPTS
              value: "{{ .Values.JVM_OPTS }}"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/kafdrop"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
              name: http