apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-java-production
resources:
  - namespace.yaml
  - ../../base/java
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - ingress-patch.yaml
 # - service-monitor.yaml
