apiVersion: v1
kind: Service
metadata:
  name: svc-app-angular
  labels:
    name: svc-app-angular
    app: app-angular
spec:
  selector:
    name: app-angular 
  type: ClusterIP
  ports:
   - name: http
     port: 80
     targetPort: {{.Values.ports.containerPort}}
     protocol: TCP