apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-java
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
          - backend:
              service:
                name: svc-java
                port:
                  number: 80
            path: /java(/|$)(.*)      
            pathType: Prefix