apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: angular-chart
  namespace: ns-angular-production
spec:
  interval: 1m
  chart:
    spec:
      chart: ../../../charts/angular/
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
