apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-java-production
resources:
  - namespace.yaml
  - ../../base/java
#  - ./infrastructure
patchesStrategicMerge:
  - helm-values.yaml