apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodejs-chart
  namespace: dso-gke-users-api
spec:
  interval: 1m
  chart:
    spec:
      chart: ../../../charts/users-api/
      version: 0.2.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    spec:
      MONGO_CONN: "mongodb://mongo-svc-chart.dso-gke-mongo.svc.cluster.local:27017/api"
    containers:
      image: europe-west1-docker.pkg.dev/capable-conduit-348311/app-java/node-app:latest 
    ports:
      API_PORT: 9495
      PROMETHEUS_PORT: 9991