apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodejs-chart
  namespace: dso-gke-users-api
spec:
  interval: 1m
  chart:
    spec:
      chart: ../../../charts/users-api/
      version: 0.1.1
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m