apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: obsidiandynamics/kafka
        env:
          - name: KAFKA_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_LISTENERS
            value: "INTERNAL://:29092,EXTERNAL://:9092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: INTERNAL://$(KAFKA_POD_IP):29092,EXTERNAL://kafkgke.svc.cluster.local:9092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INTERNAL
          - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT
            value: "6000"
          - name: KAFKA_RESTART_ATTEMPTS
            value: "10"
          - name: KAFKA_RESTART_DELAY
            value: "5"
          - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
            value: "0"        
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 2181
          name: "client"
        - containerPort: 9092
          name: "server"
