apiVersion: v1
kind: Service
metadata:
  name: svc-kafka
  labels:
    app: kafka
    name: svc-kafka
spec:
  selector:
    app: kafka
  ports:
  - name: "client"
    port: 2181
    targetPort: 2181
  - name: "server"
    port: 9092
    targetPort: 9092